name: Build and Publish

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main

      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.LOL_DETSYS_CI_SSH_PRIVATE_KEY }}

      - name: Check Nix formatting
        run: git ls-files '*.nix' | nix develop --command xargs nixfmt --check

      - name: Check Minnows Test VM
        run: |
          cd test/minnows
          nix flake check --build-all -L

  DeterminateCI:
    needs: [checks]
    uses: DeterminateSystems/ci/.github/workflows/workflow.yml@main

    permissions:
      contents: read
      id-token: write

    with:
      visibility: public
